### ISSUE TITLE
Error when deleting single pages

### ISSUE THREAD

**Issue by ICouzinaki** [souliotisg/GSTools#4]
[bcd.zip](https://github.com/souliotisg/GSTools/files/339384/bcd.zip)

Please find attached zip, unzip it and then try to reproduce the following:
delete single pages using X button 
you will reach eventually the last page with status Page 5 of 4 is displayed.
After that operations on tiff (i.e. rotation) are impossible

**Comment by souliotisg** [comment]
Fixed.
Wrong variable number in getTIFFDecoderData realActPage and actPag.
